version: "3"

services:
  database:
    image: postgres:13-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: finance_app
      POSTGRES_USER: main
      POSTGRES_PASSWORD: secret
    ports: [5432]
